version: '3'

services:
  sorabatake-foundation:
    build:
      context: .
      dockerfile: env/Dockerfile_foundation
    runtime: nvidia
    ports:
      - "8989:8989"
    volumes:
      - type: bind
        source: ./
        target: /workspace/
    working_dir: /workspace
    shm_size: '64gb'
    entrypoint:
      # - /bin/bash
      - /opt/conda/bin/jupyter-lab 
      - --allow-root
      - --ip=0.0.0.0
      - --port=8989
      - --NotebookApp.token=''